[package]
name = "pyth-lazer-solana-contract"
version = "0.4.2"
edition = "2021"
description = "Pyth Lazer Solana contract and SDK."
license = "Apache-2.0"
repository = "https://github.com/pyth-network/pyth-crosschain"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth_lazer_solana_contract"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
# idl-build = ["anchor-lang/idl-build"]

[dependencies]
pyth-lazer-protocol = { path = "../../../../sdk/rust/protocol", version = "0.7.2" }

anchor-lang = "0.28.0"
bytemuck = "1.4.0"
byteorder = "1.5.0"
solana-program = "~1.16.18"
thiserror = "2.0.3"

[dev-dependencies]
hex = "0.4.3"
solana-program-test = "~1.16.18"
solana-sdk = "~1.16.18"
tokio = { version = "1.40.0", features = ["full"] }
